### ISSUE TITLE
Unable to use the playground "no such module 'Result'

### ISSUE THREAD

**Issue by peterlondon1** [FranDepascuali/RACPlayground#5]
I am unable to use the Playground so far. I open "RACPlaygroundWorkspace.xcworkspace" per your instructions. It builds without errors. I then close "RACPlaygroundWorkspace.xcworkspace" and open the file "RACPlayground.playground", but when I get to the "Signals" page, I get an error on the "import Result" line with the following message in the log:

```
Playground execution failed: Signal.xcplaygroundpage:2:8: error: no such module 'Result'
import Result
       ^
Signal.xcplaygroundpage:3:8: error: no such module 'ReactiveCocoa'
import ReactiveCocoa
       ^
```

Any suggestions? I've searched for a solution, but nothing has worked so far. Xcode 7.3.1, other versions as follows:

```
Mac-mini:RACPlayground xxx$ ./bootstrap
*** Fetching Rex
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out Result at "2.1.1"
*** Checking out ReactiveCocoa at "v4.2.0"
*** Checking out Rex at "v0.9.0"
*** xcodebuild output can be found in /var/folders/7k/nbkx8hc5169c9kg7gyq43sjw0000gn/T/carthage-xcodebuild.eqNTWM.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "ReactiveCocoa-iOS" in ReactiveCocoa.xcworkspace
*** Building scheme "Rex-iOS" in Rex.xcworkspace
Mac-mini:RACPlayground xxx$ carthage version
0.16.2
```

**Comment by FranDepascuali** [comment]
> You need to open the playground within the workspace. Otherwise, Xcode would not be able to discover the frameworks you just built. 

@peterlondon1 Did it solve it?

**Comment by peterlondon1** [comment]
Yes, thanks!
