### ISSUE TITLE
Can't run Playground like screenshots in README file

### ISSUE THREAD

**Issue by tunidev** [FranDepascuali/RACPlayground#7]
that's what I get after following all the steps: 

<img width="950" alt="screen shot 2016-06-28 at 21 43 10" src="https://cloud.githubusercontent.com/assets/4885143/16429915/6eb679fe-3d79-11e6-8efd-18592b00803f.png">

**Comment by tunidev** [comment]
Just figure out that I need to check "Render Documentation"  field like this 

<img width="950" alt="screen shot 2016-06-28 at 21 43 10" src="https://cloud.githubusercontent.com/assets/12101394/16359517/f92cd560-3b0d-11e6-9bd3-7d26bb692ed0.png">

**Comment by FranDepascuali** [comment]
@tunidev you are right! I'll update the README! Thank you
